- fix in checking is netforking is up.
Changed files:
    nfs.init -> 1.6

diff --git a/nfs.init b/nfs.init
--- a/nfs.init
+++ b/nfs.init
@@ -20,7 +20,10 @@
 [ -f /etc/sysconfig/nfs ] && . /etc/sysconfig/nfs
 
 # Check that networking is up.
-[ "${NETWORKING}" = "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Nfs service can't be runed."
+	exit 1
+fi
 
 # Sanity check
 [ -f /etc/exports ] || exit 0
